version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana:latest-ubuntu
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana/conf:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false

  prometheus:
    image: prom/prometheus:v2.19.2
    depends_on:
      - node_exporter
      - mikrotik_exporter
      - cadvisor
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/conf:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command: ['--config.file=/etc/prometheus/prometheus.yml']

  smokeping:
    image: linuxserver/smokeping:arm32v7-latest
    restart: unless-stopped
    container_name: smokeping
    ports:
      - 8088:80
    volumes:
      - ./smokeping/conf:/config
      - ./smokeping/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kyiv

  node_exporter:
    image: prom/node-exporter:v1.0.1
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  mikrotik_exporter:
    image: fortnest/mikrotik-exporter-arm:latest
    restart: unless-stopped
    ports:
      - 9436:9436
    volumes:
      - ./mikrotik/conf:/app/conf/

  transmission_exporter:
    image: fortnest/transmission-exporter-arm:latest
    restart: unless-stopped
    ports:
      - 19091:19091
    environment:
      - TRANSMISSION_ADDR=${TRANSMISSION_ADDR}
      - TRANSMISSION_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}
      - WEB_ADDR=${WEB_ADDR}
      - WEB_PATH=${WEB_PATH}

  cadvisor:
    image: fortnest/cadvisor-arm:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - --global_housekeeping_interval=30s
      - --housekeeping_interval=5s
      - --storage_duration=1m0s
