global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    scrape_interval: 15s
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'blackbox'
    scrape_interval: 3m
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: ['http_2xx', 'tcp_connect']
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 

  - job_name: 'mikrotik'
    scrape_interval: 15s
    static_configs:
      - targets: ['mikrotik_exporter:9436']

  - job_name: 'transmission'
    scrape_interval: 15s
    static_configs:
      - targets: ['transmission_exporter:19091']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alert.rules.yml'
