global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    dns_sd_configs:
      - names:
        - 'prometheus'
        type: 'A'
        port: 9090

  - job_name: 'node'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
        - 'node_exporter'
        type: 'A'
        port: 9100

  - job_name: 'mikrotik'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
        - 'mikrotik_exporter'
        type: 'A'
        port: 9436

  - job_name: 'transmission'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
        - 'transmission_exporter'
        type: 'A'
        port: 19091

  - job_name: 'cadvisor'
    scrape_interval: 10s
    dns_sd_configs:
        - names:
          - 'cadvisor'
          type: 'A'
          port: 8080
